---
id: "enygma"
desc: "under development"
scenario: "00_default_scenario"

network:
  host: "127.0.0.1" #"commitchain-dev.parfin.corp"
  port: "8545"
  chain-id: "1337" #"149401"
  brownie-network: "development"
  seed: "localGanache"
  mnemonic: "federal unhappy avoid mistake life barrel beauty raccoon recycle unknown review link"
  accounts:
    [
      {
        address: "0x0F1013e0e46B97144b25b3131668EF99858BD8D0",
        private: "0x34d091c661db4c814d65c8ae9277b7055c0dde5a752ce5a3fdfd4ea11a8f7154",
      },

      {
        address: "0xD2C3b34Abae5664986C8cf0F14d1D434Ac894768",
        private: "0x69b5623bd1cfe22983c8849d155ca641238c18ab1b2e34c5ae943ed2ce4716b7",
      },

      {
        address: "0x9E0B331577BB37420231DAc6D199FCb4c7092B87",
        private: "0x9883c26cc126a37158c4ffcc9d401d3ffa41187d9b1a18ce4912398d22597cda",
      },

      {
        address: "0x7b5e6fcFCF5550f1B78bF5a7f32B7eE88137d156",
        private: "0x7eb9f1b270fe1d052b287322b891df041190f80b92b149b4308d5dee1a791af5",
      },

      {
        address: "0xe769049A909039C5C53EdCBF07da1b58f3960BBE",
        private: "0x678ffea2bbaf2488a3dbcad03a4aa5b54b04f0ab1d135cc659ce74866c590289",
      },

      {
        address: "0x4A1AB905d8b8c500aa796Dc96a02169a06CB7cDE",
        private: "0x40217257b8f9ce38193e802494700f987ffe45d1d55f751263ea522cf763d8dd",
      },

      {
        address: "0x428969A6b4b7Ad751d54D0D75BeA8f66977cFa75",
        private: "0x8d92a12d1719cc255d85f840a1c739824b36b29a6d4d47263dfbd0b7de9a3679",
      },

      {
        address: "0x55F6Cd76b02e4236f277ca0A88e831f407a81CDf",
        private: "0xa908223f61b565293ca4a694b81545d67c0148323ff6483c27a2881888b27ecf",
      },

      {
        address: "0xA39C23f48848ebF3B97D49f132F229fE5DB95C53",
        private: "0x25628b565fe007cec2ae79566ee68de4cb967d3b93b5b2231c4bef0e99a3c6cd",
      },

      {
        address: "0xb7d00005bc4E8A782FC552f1469b4DC355E3CD68",
        private: "0xabd09cd7bee70e813e20407b91c5d34c138322867a389879fdb204f732271fc1",
      },
    ]
